[package]
name = "loose_enum"
version = "0.1.0"
edition = "2024"

[features]
default = ["loose_bool"]
loose_bool = ["num-traits"]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0", optional = true }
num-traits = { version = "0.2", optional = true }
