[package]
name = "loose_enum"
version = "0.1.0"
edition = "2024"
description = "A macro for defining loose repr enums."
categories = ["no-std", "no-std::no-alloc", "rust-patterns"]
keywords = ["loose", "repr", "representation", "enum"]
repository = "https://github.com/AlephCubed/loose_enum"
license = "MIT OR Apache-2.0"
authors = ["AlephCubed"]

[features]
default = ["loose_bool"]
loose_bool = ["num-traits"]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0", optional = true }
num-traits = { version = "0.2", optional = true }
