[package]
name = "loose_enum"
version = "0.1.0-beta.1"
edition = "2024"
description = "A macro for defining loose repr enums."
categories = ["no-std", "no-std::no-alloc", "rust-patterns"]
keywords = ["loose", "repr", "representation", "enum"]
repository = "https://github.com/AlephCubed/loose_enum"
license = "MIT OR Apache-2.0"
authors = ["AlephCubed"]

[features]
default = ["loose_bool", "std"]
std = []
loose_bool = ["num-traits"]

serde = ["dep:serde_core"]
bevy_reflect = ["dep:bevy_reflect", "loose_bool"]

[dependencies]
bevy_reflect = { version = "0.17.3", optional = true, default-features = false }
num-traits = { version = "0.2", optional = true, default-features = false }
serde_core = { version = "1.0", optional = true, default-features = false, features = [
  "std",
] }
